server:
  port: 8880
spring:
  application:
    name: eureka1
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #是否注册到Eureka中
    registerWithEureka: true
    #是否需要去检索寻找服务，默认是true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8881/eureka/
